global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'validation'
    static_configs:
      - targets: ['validation:8001']

  - job_name: 'rule-engine'
    static_configs:
      - targets: ['rule-engine:8002']

  - job_name: 'etl'
    static_configs:
      - targets: ['etl:8003']

  - job_name: 'automation'
    static_configs:
      - targets: ['automation:8004']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8000']

  - job_name: 'dashboard'
    static_configs:
      - targets: ['dashboard:8005']

