FROM python:3.14-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY automation.py .
CMD ["uvicorn", "automation:app", "--host", "0.0.0.0", "--port", "8004"]
